'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='agri-lesson3-complete-v1';let state={done:[],seen:[],notes:{},quiz:{},first:{},stage:0};try{const old=JSON.parse(localStorage.getItem(KEY));if(old&&old.notes&&Array.isArray(old.done))state={...state,...old}}catch{}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}
function feedback(id,text,bad=false){$(id).textContent=text;$(id).classList.toggle('bad',bad)}
function toast(t){$('toast').textContent=t;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',2300)}
function complete(key){if(!state.done.includes(key)){state.done.push(key);save();renderProgress();toast('已记录一项探究成果')}}
const names=['聚焦 · 今日任务','展厅 · 回顾功能','温室 · 辨认设备','探索 · 数据旅程','中控室 · 数据查询','MQTT · 消息实验','实践 · 控制规则','会诊 · 故障排查','设计 · 思维导图','出口 · 学习手记'];const taskKeys=[null,'recall','devices','order','history','mqtt','sim','diagnosis','map','quiz'];
$('routes').innerHTML=names.map((n,i)=>`<button class="route" data-go="${i}"><strong>${String(i).padStart(2,'0')}</strong>${n}</button>`).join('');
function renderProgress(){let n=state.done.filter(k=>['recall','devices','order','history','mqtt','sim','diagnosis','map'].includes(k)).length;$('progressText').textContent=`已完成 ${n} / 8 项探究`;$('progressBar').style.width=n/8*100+'%';document.querySelectorAll('.route').forEach((e,i)=>e.classList.toggle('done',state.done.includes(taskKeys[i])))}
function go(i){stopSim();state.stage=Math.max(0,Math.min(9,i));save();document.querySelectorAll('.station').forEach((e,n)=>e.classList.toggle('active',n===state.stage));document.querySelectorAll('.route').forEach((e,n)=>{e.classList.toggle('active',n===state.stage);if(n===state.stage)e.setAttribute('aria-current','step');else e.removeAttribute('aria-current')});$('stationCount').textContent=`第 ${state.stage+1} / 10 站`;$('prevStation').disabled=state.stage===0;$('nextStation').disabled=state.stage===9;if(state.stage===9)notesPreview();window.scrollTo({top:0,behavior:'instant'})}
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(+b.dataset.go)));$('prevStation').onclick=()=>go(state.stage-1);$('nextStation').onclick=()=>go(state.stage+1);$('notebookTop').onclick=()=>go(9);$('teacherToggle').onclick=()=>{const on=document.body.classList.toggle('teacherMode');$('teacherToggle').textContent=on?'隐藏教师提示':'教师提示';$('teacherToggle').setAttribute('aria-pressed',String(on))};
function bindNote(id){$(id).value=state.notes[id]||'';$(id).oninput=()=>{state.notes[id]=$(id).value;save()}}
['prediction','explanation','transfer'].forEach(bindNote);
$('recallNo').onclick=()=>{feedback('recallFeedback','正确。监测让人看到数据；自动控制还需要有效规则、通信和能执行指令的设备。');complete('recall')};$('recallYes').onclick=()=>feedback('recallFeedback','显示读数只是监测。请再想想：谁判断何时浇水？谁真正打开阀门？',true);
const devices=[['土壤湿度传感器','感知','测量根部土壤的含水情况，转换成可读取的数据。','本课示例：土壤湿度示数 28%。','它不能直接代替水阀浇水。'],['灌溉阀门','执行','接收控制器的开关指令，配合驱动装置控制水流。','本课示例：ON / OFF。','它自身不判断土壤是否缺水。'],['网关','通信','在这个示例中汇集、转发设备数据，连接温室与网络。','转发采集设备发出的消息。','它与云平台规则引擎不是同一个角色。'],['空气温湿度传感器','感知','测量温室空气温度和相对湿度，辅助环境调节。','本课示例：30°C、65% RH。','空气湿度不能代替土壤湿度。'],['排风机','执行','在控制器驱动下促进空气流动，参与温室环境调节。','本课示例：运行 / 停止。','具体降温效果还受外界条件影响。']];
$('deviceButtons').innerHTML=devices.map((d,i)=>`<button class="btn" data-device="${i}">${i+1} ${d[0]}</button>`).join('');
function device(i){const d=devices[i];if(!state.seen.includes(i))state.seen.push(i);save();$('deviceDetail').innerHTML=`<span class="stamp">${d[1]}设备</span><h3>${i+1}. ${d[0]}</h3><dl class="deviceFacts"><dt>它的任务</dt><dd>${d[2]}</dd><dt>数据或动作</dt><dd>${d[3]}</dd><dt>注意分工</dt><dd>${d[4]}</dd></dl>`;updateDevices();if(state.seen.length===5)complete('devices')}
function updateDevices(){$('deviceProgress').textContent=`已观察 ${state.seen.length} / 5 个设备`;document.querySelectorAll('.hot').forEach(b=>b.classList.toggle('seen',state.seen.includes(+b.dataset.device)))}
document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>device(+b.dataset.device));updateDevices();
const steps=['土壤探头采集数据','采集终端或网关经网络发送','MQTT Broker 按主题分发','平台规则判断并发出指令','阀门执行，状态再次回传'];let order=[3,0,4,2,1],dragIndex=null,journeyTimer=null;
function renderOrder(){$('orderList').innerHTML=order.map((n,i)=>`<div class="orderrow" draggable="true" data-i="${i}"><b>${i+1}</b><span>${steps[n]}</span><button data-up="${i}" aria-label="第${i+1}项上移" ${i===0?'disabled':''}>↑</button><button data-down="${i}" aria-label="第${i+1}项下移" ${i===4?'disabled':''}>↓</button></div>`).join('');document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>swap(+b.dataset.up,-1));document.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>swap(+b.dataset.down,1));document.querySelectorAll('.orderrow').forEach(row=>{row.ondragstart=()=>dragIndex=+row.dataset.i;row.ondragover=e=>e.preventDefault();row.ondrop=e=>{e.preventDefault();if(dragIndex===null)return;let target=+row.dataset.i;order.splice(target,0,order.splice(dragIndex,1)[0]);dragIndex=null;renderOrder()}})}
function swap(i,d){[order[i],order[i+d]]=[order[i+d],order[i]];renderOrder()}
$('checkOrder').onclick=()=>{let ok=order.every((v,i)=>v===i);feedback('orderFeedback',ok?'顺序正确。别忘了：控制后还要重新采样或读取设备状态，才能知道动作是否奏效。':'请先从“测到了什么”开始，再找负责传递、分发、判断和执行的环节。',!ok);if(ok)complete('order')};$('resetOrder').onclick=()=>{order=[3,0,4,2,1];renderOrder();$('orderFeedback').textContent=''};renderOrder();
$('journey').innerHTML=['感知','传输','分发','判断','执行'].map((x,i)=>`${i?'<span class="flowArrow">→</span>':''}<div class="flowbox" id="flow${i}">${x}<small>${i+1}</small></div>`).join('');
const journeyText=['土壤探头测到示数 28%，采集终端获得读数。','采集终端或网关利用网络把消息发送出去。','Broker 接收 farm/1/soil 消息，交给订阅它的客户端。','平台规则发现低于示例启动阈值，发布开阀指令。','控制器驱动阀门；传感器继续采样，平台检查水分是否回升。'];
$('playJourney').onclick=()=>{clearInterval(journeyTimer);let i=0;function frame(){document.querySelectorAll('.flowbox').forEach((b,n)=>b.classList.toggle('active',n===i));$('journeyText').textContent=journeyText[i];i++;if(i===5)clearInterval(journeyTimer)}frame();journeyTimer=setInterval(frame,1500)};
const history=[{t:'09:00',v:52,temp:27},{t:'09:05',v:47,temp:27.5},{t:'09:10',v:43,temp:28},{t:'09:15',v:38,temp:29},{t:'09:20',v:33,temp:29.5},{t:'09:25',v:28,temp:30}];
function chart(values,labels,low=35,high=null){const W=600,H=265,L=45,R=16,T=20,B=38;const x=i=>L+i*(W-L-R)/Math.max(1,values.length-1),y=v=>T+(100-v)/100*(H-T-B);let svg=`<svg class="chart" role="img" aria-label="土壤湿度变化曲线，包含阈值参考线" viewBox="0 0 ${W} ${H}">`;[0,25,50,75,100].forEach(v=>svg+=`<line x1="${L}" x2="${W-R}" y1="${y(v)}" y2="${y(v)}" stroke="#e1d7c1"/><text x="8" y="${y(v)+4}" font-size="12" fill="#657464">${v}</text>`);[[low,'#b55731','启动'],[high,'#617366','停止']].filter(a=>a[0]!==null).forEach(([v,c,label])=>svg+=`<line x1="${L}" x2="${W-R}" y1="${y(v)}" y2="${y(v)}" stroke="${c}" stroke-dasharray="5 4"/><text x="${W-112}" y="${y(v)-5}" fill="${c}" font-size="11">${label} ${v}%</text>`);svg+=`<polyline fill="none" stroke="#294a3c" stroke-width="3" points="${values.map((v,i)=>x(i)+','+y(v)).join(' ')}"/>`;values.forEach((v,i)=>{svg+=`<circle cx="${x(i)}" cy="${y(v)}" r="4" fill="#b55731"/>`;if(values.length<=8||i===0||i===values.length-1)svg+=`<text text-anchor="middle" x="${x(i)}" y="${H-13}" fill="#657464" font-size="11">${esc(labels[i])}</text>`});return svg+'</svg>'}
$('historyChart').innerHTML=chart(history.map(d=>d.v),history.map(d=>d.t));$('historyRows').innerHTML=history.map(d=>`<tr><td>${d.t}</td><td>${d.v}%</td><td>${d.temp}°C</td><td>${d.v<35?'低于示例阈值':'未越界'}</td></tr>`).join('');
const cloud=[['监测','查看最新数值','把分散设备的读数集中显示。看数值时还要看单位、位置与采样时间。'],['查询','回看历史变化','查看土壤曲线和设备操作记录。单个读数不能说明持续变化，历史数据帮助分析原因。'],['报警','越界时提醒','预先设置上下限，超限后提示管理人员。阈值应结合真实作物与阶段确定。'],['控制','将决定变成指令','管理员可以远程操作；规则引擎也可以自动判断，再向设备发送指令。']];function cloudTab(i){$('cloudDetail').innerHTML=`<span class="stamp">${cloud[i][0]}</span><h3>${cloud[i][1]}</h3><p>${cloud[i][2]}</p>`;document.querySelectorAll('[data-cloud]').forEach((b,n)=>b.classList.toggle('selected',n===i))}$('cloudTabs').innerHTML=cloud.map((d,i)=>`<button class="btn" data-cloud="${i}">${d[0]}</button>`).join('');document.querySelectorAll('[data-cloud]').forEach(b=>b.onclick=()=>cloudTab(+b.dataset.cloud));cloudTab(0);
$('historyChoices').innerHTML=['09:10','09:15','09:20','09:25'].map(t=>`<button class="btn" data-time="${t}">${t}</button>`).join('');document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{const ok=b.dataset.time==='09:20';feedback('historyFeedback',ok?'对。09:15 为 38%，尚未越界；09:20 降为 33%，首次低于 35%。':'请从最早一条记录开始寻找“首次低于 35%”，不是只看最后一条。',!ok);if(ok)complete('history')});
let subscription=null,mqttSeq=0;function addLog(id,text){let li=document.createElement('li');li.textContent=text;$(id).prepend(li);while($(id).children.length>24)$(id).lastChild.remove()}
function validateTopic(t,filter=false){if(!t||t.trim()!==t||t.includes('\0')||t.includes(' '))return false;let levels=t.split('/');if(levels.some(x=>x===''))return false;if(!filter)return !/[+#]/.test(t);return levels.every((l,i)=>!/[+#]/.test(l)||l==='+'||(l==='#'&&i===levels.length-1))}
function matches(filter,topic){let f=filter.split('/'),t=topic.split('/');for(let i=0;i<f.length;i++){if(f[i]==='#')return true;if(i>=t.length||f[i]!=='+'&&f[i]!==t[i])return false}return f.length===t.length}
$('subscribe').onclick=()=>{const t=$('subTopic').value;if(!$('brokerOnline').checked)return feedback('mqttFeedback','Broker 离线，订阅请求无法建立。请先恢复连接。',true);if(!validateTopic(t,true))return feedback('mqttFeedback','本练习请使用非空层级主题；+ 要单独占一层，# 只能单独放在末层。',true);subscription=t;$('subscriptionStatus').textContent='手机已订阅：'+t;addLog('mqttLog','SUBSCRIBE '+t);feedback('mqttFeedback','订阅成功。现在重新发布一条消息，观察手机收件箱。')};
$('brokerOnline').onchange=()=>{if(!$('brokerOnline').checked){subscription=null;$('subscriptionStatus').textContent='连接中断，本实验清除订阅。恢复后请重新订阅。';feedback('mqttFeedback','Broker 已离线。试试发送消息会怎样。',true)}else feedback('mqttFeedback','Broker 已恢复，请重新确认订阅。本页不模拟持久会话。')};
$('publish').onclick=()=>{let topic=$('pubTopic').value,body;try{body=JSON.parse($('payload').value)}catch{return feedback('mqttFeedback','消息不是有效 JSON。示例：{"value":28,"unit":"%"}。实际 MQTT 并不强制使用 JSON。',true)}if(!validateTopic(topic))return feedback('mqttFeedback','本练习发布主题需层级非空、无空格，且不能含 + 或 #。请检查拼写。',true);if(!body||typeof body.value!=='number'||!Number.isFinite(body.value)||body.value<0||body.value>100||body.unit!=='%')return feedback('mqttFeedback','本实验约定 value 为 0–100 的数值，unit 为 %。这个约定属于应用数据格式。',true);mqttSeq++;if(!$('brokerOnline').checked){addLog('mqttLog',`${mqttSeq}. 发送失败：Broker 离线`);return feedback('mqttFeedback','消息未送到 Broker，手机没有新消息。',true)}['pubNode','brokerNode'].forEach(id=>{$(id).classList.remove('flash');void $(id).offsetWidth;$(id).classList.add('flash')});addLog('mqttLog',`${mqttSeq}. PUBLISH ${topic} ${JSON.stringify(body)}`);if(subscription&&matches(subscription,topic)){$('subNode').classList.remove('flash');void $('subNode').offsetWidth;$('subNode').classList.add('flash');$('inbox').textContent=`主题：${topic}\n消息：${JSON.stringify(body,null,2)}\n接收序号：${mqttSeq}`;feedback('mqttFeedback','投递成功：手机订阅与发布主题匹配。试着修改棚号，再观察对照结果。');addLog('mqttLog','DELIVER 到手机');state.notes.mqttEvidence='手机订阅 '+subscription+'，收到主题 '+topic+'，内容 '+JSON.stringify(body);save();complete('mqtt')}else{feedback('mqttFeedback',subscription?'Broker 已收到消息，但主题与手机订阅不匹配。手机收件箱保持上一条内容。':'Broker 已收到消息，但手机尚未订阅。订阅后需要再发布一次。',true);addLog('mqttLog','未向手机投递：无匹配订阅')}};
let sim={soil:28,time:0,on:false,last:28,values:[28],opened:false,closed:false},simTimer=null;function stopSim(){if(simTimer){clearInterval(simTimer);simTimer=null}$('simPlay').textContent='连续运行'}
function thresholds(){const low=Number($('low').value),high=Number($('high').value);if(!$('low').value||!$('high').value||!Number.isFinite(low)||!Number.isFinite(high)||low<5||high>95||low>=high){feedback('simFeedback','请输入合法阈值：5 ≤ 启动阈值 < 停止阈值 ≤ 95。',true);stopSim();return null}return{low,high}}
function renderSim(){const limits=thresholds()||{low:35,high:55};$('soilValue').textContent=Math.round(sim.soil)+'%';$('simTime').textContent=sim.time+' 分';$('valveState').textContent=sim.on?'阀门已打开':'阀门关闭';$('valvePanel').classList.toggle('on',sim.on);$('lastReading').textContent='平台最近接收：'+sim.last+'%'+(['network','sensor'].includes($('fault').value)?'（缺少新有效数据，可能已过期）':'');let vals=sim.values.slice(-16),start=Math.max(0,sim.values.length-16);$('simChart').innerHTML=chart(vals,vals.map((_,i)=>String(start+i)),limits.low,limits.high)}
function simStep(){const l=thresholds();if(!l)return;const fault=$('fault').value;sim.time++;let text='';if(fault==='network'||fault==='sensor'){sim.on=false;text=fault==='network'?'网络断开：平台收不到新消息，课堂模型暂停自动控制并关阀。':'无有效采样：不能按缺失值做判断，课堂模型暂停自动控制并关阀。'}else{sim.last=Math.round(sim.soil);if($('controlMode').value==='auto'){if(sim.soil<l.low){if(fault==='valve'){sim.on=false;text='平台已发布 ON，但阀门反馈仍关闭。应检查执行环节。'}else{sim.on=true;sim.opened=true;text='收到低土壤示数，规则命中，发送 ON，阀门反馈已打开。'}}else if(sim.soil>=l.high){const wasOn=sim.on;sim.on=false;if(wasOn&&sim.opened)sim.closed=true;text='达到停止阈值，发送 OFF，阀门关闭。'}else text='位于两个阈值之间，保持原状态，减少临界值附近频繁开关。'}else text='人工模式：平台记录读数，设备动作由人工按钮决定。'}sim.soil=Math.max(10,Math.min(90,sim.soil+(sim.on?8:-2)));sim.values.push(Math.round(sim.soil));addLog('simLog',`${sim.time} 分｜${text} 现场更新为 ${Math.round(sim.soil)}%。`);feedback('simFeedback',text,fault!=='none');if(sim.opened&&sim.closed){feedback('simTask','你已观察到自动开阀和自动关阀。下一步可以注入故障，检验系统边界。');state.notes.controlEvidence='已观察自动开阀与关阀；阈值 '+l.low+'/'+l.high+'；土壤示数序列 '+sim.values.join('、')+'。';save();complete('sim')}renderSim()}
$('simStep').onclick=simStep;$('simPlay').onclick=()=>{if(simTimer)return stopSim();if(!thresholds())return;$('simPlay').textContent='暂停运行';simTimer=setInterval(simStep,1400)};$('simReset').onclick=()=>{stopSim();sim={soil:28,time:0,on:false,last:28,values:[28],opened:false,closed:false};$('fault').value='none';$('simLog').innerHTML='';feedback('simFeedback','实验已重置。初始土壤示数 28%。');feedback('simTask','本轮闭环任务尚未完成。');renderSim()};['low','high'].forEach(id=>$(id).onchange=renderSim);$('fault').onchange=()=>{stopSim();sim.on=false;renderSim();feedback('simFeedback','故障设置已改变，推进一步查看证据。')};$('controlMode').onchange=()=>{stopSim();sim.on=false;renderSim();$('manualOpen').disabled=$('controlMode').value!=='manual';$('manualClose').disabled=$('controlMode').value!=='manual'};
function manual(on){if($('controlMode').value!=='manual')return feedback('simFeedback','请先切换到人工控制模式。',true);if($('fault').value!=='none')return feedback('simFeedback','当前存在故障，本模型不执行人工开关请求。请先恢复设备正常。',true);sim.on=on;addLog('simLog','人工指令 '+(on?'ON':'OFF'));feedback('simFeedback','人工命令已执行。推进时间，查看现场土壤变化。');renderSim()}
$('manualOpen').onclick=()=>manual(true);$('manualClose').onclick=()=>manual(false);$('manualOpen').disabled=true;$('manualClose').disabled=true;renderSim();
const cases=[{title:'病例 A：手机一直没有新数据',clues:'终端读数正常；Broker 日志显示收到 farm/1/soil；手机订阅的是 farm/2/soil。',opts:['优先核对手机订阅主题','更换全部土壤探头','把灌溉阀永久打开'],key:0,why:'Broker 已收到数据，首先核对接收者订阅的棚号和主题。'}, {title:'病例 B：平台显示“已开阀”，土壤仍变干',clues:'规则日志存在 ON 指令；网络在线；设备回报阀门仍为 OFF。',opts:['把 MQTT 改成 Wi-Fi','优先检查阀门驱动与设备状态反馈','只清除告警文字'],key:1,why:'指令存在与设备实际执行不同。现场反馈提示应核查执行设备和驱动。'}, {title:'病例 C：大屏数值看起来很稳定',clues:'所有显示值停留在 09:10；当前已是 09:25；网关心跳丢失。',opts:['说明温室完全没有变化','调高报警阈值即可','优先检查连接与时间戳，标识过期数据'],key:2,why:'稳定的旧数值不等于实时环境稳定。先检查链路，避免把旧数据当新数据。'}];let casesDone=new Set();$('diagnosis').innerHTML=cases.map((c,i)=>`<article class="paper" style="margin-bottom:20px"><span class="stamp">证据卡 ${i+1}</span><h3>${c.title}</h3><div class="case">${c.clues}</div>${c.opts.map((o,j)=>`<button class="quizOption" data-case="${i}" data-answer="${j}">${'ABC'[j]}. ${o}</button>`).join('')}<div class="feedback" id="case${i}" aria-live="polite"></div></article>`).join('');document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>{const i=+b.dataset.case,correct=+b.dataset.answer===cases[i].key;feedback('case'+i,correct?cases[i].why:'这个动作没有对应当前证据。先找出日志中已经确认正常的环节。',!correct);if(correct){casesDone.add(i);b.classList.add('correct');if(casesDone.size===3){complete('diagnosis');feedback('diagnosisResult','三例会诊完成：先看证据，再定位环节，最后核查。')}}});
const branches=[['数据与设备','例如：土壤探头、网关、网络、阀门'],['平台的功能','例如：监测、存储、历史查询、报警、控制'],['MQTT 的关系','例如：发布者、Broker、订阅者、主题'],['一条控制规则','写出测量对象、启动条件、停止条件和动作']];$('mapBranches').innerHTML=branches.map((b,i)=>`<div class="mapbranch"><h3>${b[0]}</h3><label>分支 ${i+1}<textarea id="map${i}" placeholder="${b[1]}"></textarea></label></div>`).join('');branches.forEach((_,i)=>bindNote('map'+i));$('checkMap').onclick=()=>{const ids=['map0','map1','map2','map3','explanation'],missing=ids.filter(id=>$(id).value.trim().length<5);feedback('mapFeedback',missing.length?'还有 '+missing.length+' 处需要补充至少一句说明，请检查四个分支与系统解释。':'字段结构完整。请用同伴量规核对内容准确性，完成自己的连线解释。',!!missing.length);if(!missing.length)complete('map')};$('mapExample').onclick=()=>{$('mapReference').hidden=!$('mapReference').hidden;$('mapReference').innerHTML='<h3>参考关键词与关系</h3><p>数据：土壤示数、时间戳；设备：采集终端、网关、阀门。平台：显示、存储、查询、报警、控制。MQTT：终端发布 farm/1/soil，Broker 分发，规则程序订阅。规则：有效土壤示数低于 35% 开阀，达到 55% 关阀（教学示例）。</p><p>控制器还可订阅 farm/1/valve，接收 ON/OFF；设备状态回传帮助核对是否真正执行。</p>'};
const quiz=[['平台最早在哪个时刻发现土壤示数低于 35%？',['09:15（38%）','09:20（33%）','09:25（28%）'],1,'首次越界为 09:20。最新值与首次越界时刻是不同信息。'],['MQTT 在本课中主要解决什么问题？',['规定设备消息怎样发布和订阅','测量土壤水分','直接扩大无线覆盖距离'],0,'MQTT 是消息协议，测量由传感器承担，无线覆盖与网络技术有关。'],['手机订阅 farm/1/soil，发布 farm/2/soil 时会怎样？',['一定收到，因为都是土壤','自动打开一号棚水阀','精确主题不匹配，手机不接收'],2,'没有使用通配符时，主题要匹配；棚号不同不能混淆。'],['下列哪项最能说明真正完成了灌溉？',['界面有一个 ON 按钮','平台存在已发出的指令','阀门反馈已打开，后续土壤读数有相应变化'],2,'实际反馈与后续采样为动作效果提供证据。'],['为什么同时设置启动 35% 和停止 55%？',['让系统在临界值附近避免频繁开关','MQTT 要求必须用这两个数','所有番茄都用同一阈值'],0,'两阈值演示保持区间。数值为教学约定，真实阈值需要专门确定。'],['空气湿度低，是否足以判断根部土壤缺水？',['一定足够','不够，还应检查土壤等相关信息','只需检查 MQTT 主题长度'],1,'空气与土壤是不同测量对象，不应混用。'],['Broker 已收到消息，手机却收不到。优先检查什么？',['网络一定全部损坏','手机订阅主题和连接状态','立刻增加灌溉时间'],1,'按已知证据缩小排查范围。先核对订阅与客户端连接。'],['主题和 JSON 的说法，哪项正确？',['MQTT 强制每条消息都使用 JSON','主题决定接收关系，JSON 是本实验的消息内容约定','Broker 必须理解 JSON 才能分发'],1,'MQTT 根据主题分发；内容格式由应用约定，Broker 无需解析农业语义。']];let qi=0;
function renderQuiz(){let q=quiz[qi],choice=state.quiz[qi],answered=choice!==undefined;$('quizArea').innerHTML=`<span class="stamp">出口检测 ${qi+1}</span><h3>${q[0]}</h3>${q[1].map((o,i)=>`<button class="quizOption ${answered&&choice===i?(i===q[2]?'correct':'incorrect'):''}" data-quiz="${i}">${'ABC'[i]}. ${o}</button>`).join('')}${answered?`<div class="feedback ${choice===q[2]?'':'bad'}">${choice===q[2]?'回答正确。':'请再试一次。'}${q[3]}</div>`:''}`;document.querySelectorAll('[data-quiz]').forEach(b=>b.onclick=()=>{let i=+b.dataset.quiz;if(state.first[qi]===undefined)state.first[qi]=i;state.quiz[qi]=i;save();renderQuiz();if(quiz.every((q,n)=>state.quiz[n]===q[2]))complete('quiz');notesPreview()});$('quizPosition').textContent=`${qi+1} / ${quiz.length}`;$('quizPrev').disabled=qi===0;$('quizNext').disabled=qi===7;let firstScore=quiz.filter((q,i)=>state.first[i]===q[2]).length,now=quiz.filter((q,i)=>state.quiz[i]===q[2]).length;$('quizResult').textContent=`首次作答 ${firstScore}/8；当前掌握 ${now}/8；已尝试 ${Object.keys(state.first).length}/8 题。`}
$('quizPrev').onclick=()=>{qi=Math.max(0,qi-1);renderQuiz()};$('quizNext').onclick=()=>{qi=Math.min(7,qi+1);renderQuiz()};renderQuiz();
function notes(){const n=state.notes;return `智慧农业示范区 · 第3课参观手记\n\n一、出发前的猜想\n${n.prediction||'（待填写）'}\n\n二、四个思维导图分支\n${branches.map((b,i)=>b[0]+'：\n'+(n['map'+i]||'（待填写）')).join('\n\n')}\n\n三、我的系统解释\n${n.explanation||'（待填写）'}\n\n四、迁移到教室\n${n.transfer||'（待填写）'}\n\n五、实验记录\nMQTT：${n.mqttEvidence||'（未完成有效投递）'}\n控制实验：${n.controlEvidence||'（未完成自动开关阀）'}\n\n六、学习记录\n已观察设备 ${state.seen.length}/5\n已完成探究：${state.done.map(k=>({recall:'功能回顾',devices:'设备观察',order:'链路排序',history:'历史读图',mqtt:'消息投递',sim:'控制闭环',diagnosis:'故障会诊',map:'作品结构',quiz:'检测订正'}[k]||k)).join('、')||'暂无'}\n${$('quizResult').textContent}\n\n本课实验数值和阈值均为教学模拟。`}
function notesPreview(){$('notebookPreview').textContent=notes()}
$('refreshNotes').onclick=notesPreview;$('exportNotes').onclick=()=>{const url=URL.createObjectURL(new Blob(['\ufeff'+notes()],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='我的智慧农业参观手记.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('参观手记已生成')};$('printNotes').onclick=()=>{notesPreview();window.print()};renderProgress();go(state.stage||0);
