(()=>{const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const key='agri-game-v2'; let S=Object.assign({energy:100,score:0,done:[],notes:'',soil:28,temp:30,valve:false,sub:null,log:[],started:Date.now(),alarm:100,cycles:0},JSON.parse(localStorage.getItem(key)||'{}')); const save=()=>localStorage.setItem(key,JSON.stringify(S));
const missions=[['greenhouse','温室现场','拖动模块，修复“感知→执行”链路',20],['gateway','通信节点','把采集数据送进 MQTT Broker',20],['control','网络中控室','发布、订阅并捕获一条 MQTT 消息',25],['farm','农场设备','调阈值、跑规则，完成一次自动灌溉',30]];
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)} function render(){ $('#energy').textContent=Math.max(0,Math.round(S.energy));$('#score').textContent=S.score;$('#level').textContent=S.score>=75?'温室守护者':S.score>=45?'消息调度员':S.score>=20?'现场侦察员':'新手工程师';$('#soil').textContent=S.soil+'%';$('#temp').textContent=S.temp+'°C';$('#valve').textContent=S.valve?'开启':'关闭';$('#notes').value=S.notes;$('#alarmBar').style.width=S.alarm+'%';$('#missionList').innerHTML=missions.map(m=>`<button class="mission ${S.done.includes(m[0])?'done':''}" data-open="${m[0]}"><span>${S.done.includes(m[0])?'✓':'○'}</span><b>${m[1]}</b><small>${m[2]}</small><em>+${m[3]}能量</em></button>`).join('');$$('[data-open]').forEach(e=>e.onclick=()=>openZone(e.dataset.open));save()}
function reward(id,n){if(!S.done.includes(id)){S.done.push(id);S.score+=n;S.energy=Math.min(100,S.energy+12);toast('任务完成！系统恢复能量 +12');render()}}
function openZone(id){let title=missions.find(x=>x[0]===id)?.[1]||'守护终端';$('#consoleTitle').textContent=title;$('#consoleHint').textContent='动手操作，观察数据如何流动';$('#console').classList.add('active');let b=$('#consoleBody'); if(id==='greenhouse') greenhouse(b); if(id==='gateway') gateway(b); if(id==='control') control(b); if(id==='farm') farm(b)}
function greenhouse(b){let items=['土壤探头','采集终端','主题消息','阀门驱动'],slots=['感知层','采集层','消息层','执行层'];b.innerHTML=`<h2>修复温室控制链</h2><p>把四个模块拖进正确的层级。每放对一个，数据链会亮起。</p><div class="dragShelf">${items.map((x,i)=>`<button class="chip" draggable="true" data-i="${i}">${x}</button>`).join('')}</div><div class="dropGrid">${slots.map((x,i)=>`<div class="dropSlot" data-i="${i}"><b>${x}</b><small>拖到这里</small></div>`).join('')}</div><div class="feedback" id="feed">等待你的布线……</div>`;let ans=[0,1,2,3];$$('.chip').forEach(c=>c.ondragstart=e=>e.dataTransfer.setData('i',c.dataset.i));$$('.dropSlot').forEach(s=>{s.ondragover=e=>e.preventDefault();s.ondrop=e=>{let i=e.dataTransfer.getData('i');if(i===s.dataset.i&&!s.classList.contains('ok')){s.classList.add('ok');s.innerHTML='<b>✓ '+items[i]+'</b>';$('#feed').textContent='连接正确，继续寻找下一段链路。';if($$('.dropSlot.ok').length===4){$('#feed').textContent='感知—采集—消息—执行，闭环已恢复！';reward('greenhouse',20);}}else toast('这个模块与该层级不匹配')}})}
function gateway(b){let order=['采集','网络发送','Broker分发','平台判断','阀门执行'];b.innerHTML=`<h2>通信节点：让消息跑起来</h2><p>点击卡片排出一条完整路径。MQTT负责消息的发布与订阅，网络负责把消息送达。</p><div class="routeCards">${order.map((x,i)=>`<button data-i="${i}">${x}</button>`).join('')}</div><div class="routeLine" id="routeLine">尚未连通</div>`;let chosen=[];$$('.routeCards button').forEach(c=>c.onclick=()=>{if(chosen.includes(+c.dataset.i))return;chosen.push(+c.dataset.i);c.classList.add('picked');$('#routeLine').textContent=chosen.map(i=>order[i]).join('  →  ');if(chosen.length===5){if(chosen.join()==='0,1,2,3,4'){fly();reward('gateway',20);$('#routeLine').textContent+='  ✓ 消息已送达';}else{toast('顺序不对：先采集，再发送，再由 Broker 分发');chosen=[];$$('.routeCards button').forEach(x=>x.classList.remove('picked'));}}})}
function fly(){['#packet1','#packet2'].forEach((s,i)=>{let p=$(s);p.classList.remove('fly');void p.offsetWidth;p.classList.add('fly');setTimeout(()=>p.classList.remove('fly'),1600)});$('#story').textContent='数据包正在从温室穿过网络，抵达云平台……'}
function control(b){b.innerHTML=`<h2>网络中控室：MQTT 消息实验</h2><p>主题像“频道地址”，载荷是消息内容。试着订阅后再发布一条 JSON 数据。</p><div class="mqttGrid"><div><label>订阅主题 <input id="subTopic" value="farm/1/soil"></label><button class="primary" id="subscribe">订阅频道</button><div class="broker"><i></i> MQTT Broker <small>在线</small></div></div><div><label>发布主题 <input id="pubTopic" value="farm/1/soil"></label><label>载荷 <textarea id="payload">{"value":22,"unit":"%"}</textarea></label><button class="primary" id="publish">发布消息 ●</button></div></div><div class="inbox" id="inbox">收件箱为空，等待消息……</div>`;$('#subscribe').onclick=()=>{S.sub=$('#subTopic').value.trim();$('#inbox').textContent='已订阅：'+S.sub+'，等待匹配消息';save();toast('订阅成功')};$('#publish').onclick=()=>{let t=$('#pubTopic').value.trim(),raw=$('#payload').value;try{let data=JSON.parse(raw);fly();if(S.sub&&match(S.sub,t)){S.log.push({t,data});$('#inbox').innerHTML=`<b>捕获消息</b><pre>${JSON.stringify(data,null,2)}</pre>`;reward('control',25)}else{$('#inbox').textContent='消息已发布，但没有匹配的订阅者。'}}catch(e){toast('载荷必须是合法 JSON')}}}
function match(sub,t){if(sub===t)return true;let a=sub.split('/'),b=t.split('/');return a.length===b.length&&a.every((x,i)=>x==='+'||x===b[i])}
function farm(b){b.innerHTML=`<h2>农场设备：调节自动灌溉规则</h2><p>拖动阈值，观察系统在“低于下限”时开启阀门，在“达到上限”时关闭阀门。</p><div class="gauges"><div><b>土壤湿度</b><strong id="gsoil">${S.soil}%</strong><meter id="meter" min="0" max="100" value="${S.soil}"></meter></div><div><b>空气温度</b><strong>${S.temp}°C</strong><meter min="0" max="45" value="${S.temp}"></meter></div></div><div class="sliders"><label>开启下限 <input id="low" type="range" min="10" max="45" value="30"><output>30%</output></label><label>关闭上限 <input id="high" type="range" min="45" max="90" value="60"><output>60%</output></label></div><div class="farmBtns"><button class="primary" id="step">运行一个时间片</button><button class="ghost" id="fault">模拟网络抖动</button></div><div class="feedback" id="ruleFeed">规则待运行。</div>`;let low=$('#low'),high=$('#high');$$('.sliders input').forEach(x=>x.oninput=()=>x.nextElementSibling.value=x.value);$('#step').onclick=()=>{let l=+low.value,h=+high.value;if(l>=h){toast('上限要高于下限');return}if(S.soil<l){S.valve=true;S.soil=Math.min(100,S.soil+14);$('#ruleFeed').textContent='土壤低于下限 → 云平台发布 OPEN → 阀门开启';}else if(S.soil>=h){S.valve=false;S.soil=Math.max(0,S.soil-2);S.cycles++;$('#ruleFeed').textContent='土壤达到上限 → 云平台发布 CLOSE → 阀门关闭';}else{$('#ruleFeed').textContent='数据在阈值区间内，保持当前状态。'}render();$('#gsoil').textContent=S.soil+'%';$('#meter').value=S.soil;if(S.cycles>0&&S.valve===false)reward('farm',30)};$('#fault').onclick=()=>{$('#ruleFeed').textContent='网络抖动：命令已发布，反馈延迟。系统保持安全状态，等待下一次确认。';toast('故障已记录到工程师笔记')};}
$('#closeConsole').onclick=()=>$('#console').classList.remove('active');$$('.zone').forEach(z=>z.onclick=()=>openZone(z.dataset.zone));$('#help').onclick=$('#openManual').onclick=()=>{ $('#modalBody').innerHTML='<h2>任务手册｜智慧农业物联网</h2><p><b>情境：</b>温室里的传感器持续采集土壤湿度，网络把数据送到云平台，规则决定是否灌溉。</p><p><b>MQTT：</b>一种轻量级消息发布/订阅协议。主题用于分类，Broker负责转发，载荷承载数据。</p><p><b>工程判断：</b>土壤湿度、空气温度、空气湿度是不同指标；阈值只是本关模拟参数，真实农业需要结合传感器校准与安全策略。</p><hr><p>建议路线：先探索地图，再完成拖拽、连线、消息实验和规则实验。你可以重复操作，不会因失败扣分。</p>';$('#modal').classList.add('show')};$('#modalClose').onclick=()=>$('#modal').classList.remove('show');$('#saveNotes').onclick=()=>{S.notes=$('#notes').value;save();toast('笔记已保存')};$('#resetGame').onclick=()=>{if(confirm('确定重置本局进度吗？')){localStorage.removeItem(key);location.reload()}};setInterval(()=>{S.energy=Math.max(0,S.energy-.15);S.alarm=Math.max(20,S.alarm-.05);render()},5000);render();
})();
